In [6]:
import numpy as np

In [7]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b.shape

(3, 3)

In [10]:
b[1,1]

5

In [11]:
b[1,0:1]

array([4])

In [12]:
a = np.array([[1,2,3],[4,5,6]])

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
g=a.transpose()
g

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
d=a.reshape((3,2))
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
d.shape


(3, 2)

In [17]:
f=d.reshape((2,3))
f

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
c= d.transpose()

In [19]:
c

array([[1, 3, 5],
       [2, 4, 6]])

In [20]:
import csv

In [21]:
with open('E:\Demo Datasets\iris_data.csv',mode='r') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        print(row)
        

['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']
['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa']
['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa']
['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa']
['4', '4.6', '3.1', '1.5', '0.2', 'Iris-setosa']
['5', '5.0', '3.6', '1.4', '0.2', 'Iris-setosa']
['6', '5.4', '3.9', '1.7', '0.4', 'Iris-setosa']
['7', '4.6', '3.4', '1.4', '0.3', 'Iris-setosa']
['8', '5.0', '3.4', '1.5', '0.2', 'Iris-setosa']
['9', '4.4', '2.9', '1.4', '0.2', 'Iris-setosa']
['10', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa']
['11', '5.4', '3.7', '1.5', '0.2', 'Iris-setosa']
['12', '4.8', '3.4', '1.6', '0.2', 'Iris-setosa']
['13', '4.8', '3.0', '1.4', '0.1', 'Iris-setosa']
['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa']
['15', '5.8', '4.0', '1.2', '0.2', 'Iris-setosa']
['16', '5.7', '4.4', '1.5', '0.4', 'Iris-setosa']
['17', '5.4', '3.9', '1.3', '0.4', 'Iris-setosa']
['18', '5.1', '3.5', '1.4', '0.3', 'Iris-setosa']
['19', '5.7', '3.8', '1.7

In [25]:
data = np.loadtxt('E:\Demo Datasets\iris_data.csv', delimiter=',',skip_header=1)

TypeError: loadtxt() got an unexpected keyword argument 'skip_header'

In [29]:
data = np.genfromtxt('E:\Demo Datasets\iris_data.csv', delimiter=',',names=True, dtype=None) 

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8808\2865464082.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  data = np.genfromtxt('E:\Demo Datasets\iris_data.csv', delimiter=',',names=True, dtype=None)


In [30]:
data

array([(  1, 5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (  2, 4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (  3, 4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (  4, 4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (  5, 5. , 3.6, 1.4, 0.2, b'Iris-setosa'),
       (  6, 5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (  7, 4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (  8, 5. , 3.4, 1.5, 0.2, b'Iris-setosa'),
       (  9, 4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       ( 10, 4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       ( 11, 5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       ( 12, 4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       ( 13, 4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       ( 14, 4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       ( 15, 5.8, 4. , 1.2, 0.2, b'Iris-setosa'),
       ( 16, 5.7, 4.4, 1.5, 0.4, b'Iris-setosa'),
       ( 17, 5.4, 3.9, 1.3, 0.4, b'Iris-setosa'),
       ( 18, 5.1, 3.5, 1.4, 0.3, b'Iris-setosa'),
       ( 19, 5.7, 3.8, 1.7, 0.3, b'Iris-setosa'),
       ( 20, 5.1, 3.8, 1.5, 0.3, b'Iris-setosa'),


In [31]:
print(data[0,1])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed