In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.3.0


 #introduction to tensors

In [3]:
# SCALAR 
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
 scalar.item()   #get tensor back as python int

7

In [6]:
# vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [7]:
vector.shape

torch.Size([2])

### MATRIX


In [8]:

MATRIX = torch.tensor([[[7,8],[9,10]],[[2,1],[3,4]]])

In [9]:
MATRIX

tensor([[[ 7,  8],
         [ 9, 10]],

        [[ 2,  1],
         [ 3,  4]]])

In [10]:
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])
print(MATRIX.size())

3
torch.Size([2, 2, 2])
tensor([[ 7,  8],
        [ 9, 10]])
torch.Size([2, 2, 2])


In [11]:
# TENSORS
TENSOR = torch.tensor([[[[[1,2,3],
                        [3,6,9],
                        [2,4,5]]]]])
TENSOR.shape
TENSOR.ndim


5

In [12]:
TENSOR.dtype

torch.int64

In [13]:
 exm = torch.tensor([[[[1],
                       [2],
                       [3],
                       [4]]]])
exm.shape

torch.Size([1, 1, 4, 1])

In [14]:
exm2 = torch.tensor([[[[[1,2],
                        [2,3],
                        [4,5],
                        [6,7],
                        [8,9]]]]])

In [15]:
exm2.shape

torch.Size([1, 1, 1, 5, 2])

### RANDOM TENDSORS

In [16]:
random_tensor = torch.randint(0,10,(3,3))
random_tensor

tensor([[3, 2, 4],
        [7, 9, 7],
        [1, 5, 5]])

In [17]:
random_tensor.ndim

2

### Create a random tensor with similar shape to an image tensor

In [18]:
random_image_size_tensor = torch.rand(size=(224,224,3))

In [19]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
random_tensor.dtype

torch.int64

### create a tensors of all zeros

In [21]:
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
zeros*ones

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [24]:
#Create a range fo values in tensors
a=torch.arange(1,11) 
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#creating tensors like
ten_zeros = torch.ones_like(a)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes
***NOTE*** : *3 major errors that mat occur,*
1. Tensors not in right datatype
2. Tensors not in right shape
3. Tensors not on the right device

In [26]:
float_32_tensor = torch.tensor([5.09,6.0,7.0],
                               dtype=torch.float16,
                                device=None,
                               requires_grad=False)
float_32_tensor

tensor([5.0898, 6.0000, 7.0000], dtype=torch.float16)

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([5.0898, 6.0000, 7.0000], dtype=torch.float16)

In [28]:
float_32_tensor*float_16_tensor

tensor([25.9062, 36.0000, 49.0000], dtype=torch.float16)

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [30]:
float_16_tensor*int_32_tensor

tensor([15.2656, 36.0000, 63.0000], dtype=torch.float16)

### Getting info from tensor

In [31]:
some_tensor= torch.rand(3,4)
some_tensor

tensor([[0.3273, 0.6859, 0.1979, 0.9810],
        [0.0326, 0.4845, 0.8431, 0.0218],
        [0.6580, 0.6888, 0.8026, 0.6232]])

In [32]:
print(some_tensor)
print(f"Datatype of the tensor : {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tenspr is on: {some_tensor.device}")

tensor([[0.3273, 0.6859, 0.1979, 0.9810],
        [0.0326, 0.4845, 0.8431, 0.0218],
        [0.6580, 0.6888, 0.8026, 0.6232]])
Datatype of the tensor : torch.float32
Shape of tensor: torch.Size([3, 4])
Device tenspr is on: cpu


### Manupulating tensors
*Tensors operation:*
1. Addition
2. Sub
3. Multiplication ( Element wise)
4. Division
5. Matrix Multiplication

In [33]:
#ADDITION
tensor = torch.tensor([1,2,3])
print(tensor + 10)

tensor([11, 12, 13])


In [34]:
#multiplication
print(tensor*10)

tensor([10, 20, 30])


In [35]:
#PyTorch in-built fn.
print(torch.mul(tensor,10))
print(torch.div(tensor,2))
print(torch.add(tensor,3))
print(torch.sub(tensor,1))

tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])
tensor([4, 5, 6])
tensor([0, 1, 2])


## Matrix Multiplication
##### Multiplication in neural networks and deep learning:
1. Element wise multiplication
2. Matrix multiplication (dot product)

#### Element wise

In [36]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


##### Matrix Multiplication

In [37]:
%%time
print(torch.matmul(tensor, tensor))


tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [38]:
#matrix multiplication by hands
1*1 + 2*2 + 3*3

14

In [39]:
%%time
value = 0
print(len(tensor))
for i in range(len(tensor)):
    value += tensor[i] * tensor [i]
print(value)



3
tensor(14)
CPU times: total: 0 ns
Wall time: 1 ms


#### matrix shape errors

In [40]:
tensor_1 = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
tensor_2 = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

In [41]:
tensor_1.shape, tensor_2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

##### Cant multiply matrix with different inner dimension
#### SO TRANSPOSING 

In [42]:
tensor_2.T, tensor_2.T.shape

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [43]:
torch.matmul(tensor_1, tensor_2.T)

tensor([[ 27,  61,  95],
        [ 30,  68, 106],
        [ 33,  75, 117]])

### Finding the min max, mean, sum, ets, (tensor aggregation)

In [44]:
#create a tensor
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
#find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [46]:
#find the max
torch.max(x), x.max()

(tensor(9), tensor(9))

In [47]:
#mean. It requires a float 32.
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(5.), tensor(5.))

In [48]:
#find sum
torch.sum(x) , x.sum()

(tensor(45), tensor(45))

#### To find the position of the min and max value.

In [49]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# To find the min position 
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [51]:
# To find the max value position
x.argmax() , torch.argmax(x)

(tensor(8), tensor(8))

#### Reshaping, view, Stacking, Squeeze, Unsqueeze, Permute

In [52]:
#Reshape:
a, a.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [53]:
#add an extra dimension
a_reshaped = a.reshape(1,10)
a_reshaped, a_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [54]:
# change the view
z = a.view(2,5)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [55]:
# z[0]== 2
z[:,0]=5
z,a

(tensor([[ 5,  2,  3,  4,  5],
         [ 5,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10]))

In [56]:
a_reshaped


tensor([[ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10]])

In [57]:
#stack tensors on top of each other
# a_stacked = torch.stack([a_reshaped,z], dim = 0)
# a_stacked

##### squeeze and unsqueeze


In [58]:
c = torch.zeros(2,1,2,1,2)

c, c.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [59]:
 d = torch.squeeze(c)
d

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [60]:
d.size()

torch.Size([2, 2, 2])

In [61]:
e=d.unsqueeze(dim=0)
e

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])

In [62]:
e.shape

torch.Size([1, 2, 2, 2])

In [63]:
#squeezed
print(f"Previous tensor: {a_reshaped}")
print(f"Previous shape: {a_reshaped.shape}")

a_squeezed = a_reshaped.squeeze()
print(f"New tensor: {a_squeezed}")
print(f"New tnesor shape: {a_squeezed.shape}")

Previous tensor: tensor([[ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10]])
Previous shape: torch.Size([1, 10])
New tensor: tensor([ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10])
New tnesor shape: torch.Size([10])


In [64]:
#unsqueezed
print(f"Before : {a_squeezed}")
print(f"Shape before unsqueezing:{a_squeezed.shape}")

a_unsqueezed = a_squeezed.unsqueeze(dim=0)

print(f"After unsqueezing: {a_unsqueezed}")
print(f"Shape after squeezing: {a_unsqueezed.shape}")

Before : tensor([ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10])
Shape before unsqueezing:torch.Size([10])
After unsqueezing: tensor([[ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10]])
Shape after squeezing: torch.Size([1, 10])


 #### Permute 

In [65]:
x_orginal = torch.rand(size=(220, 330, 2))
x_permuted = x_orginal.permute(2,0,1)
print(f"Before permuting:{x_orginal.shape}")
print(f"After permuting:{x_permuted.shape}")

Before permuting:torch.Size([220, 330, 2])
After permuting:torch.Size([2, 220, 330])


## INDEXING (Selecting data form tensors)

In [66]:
print(x)
print(x.shape)
x= x.unsqueeze(dim=0)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])


In [67]:
x, x.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [69]:
x= x.reshape(1,3,3)

In [ ]:
x, x.shape

In [74]:
#index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
x[0,1,2], x[0][1][2]

(tensor(6), tensor(6))

In [79]:
x[0,0]

tensor([1, 2, 3])

In [88]:
x[:,:,1], x[:,2,1] , x[:0]

(tensor([[2, 5, 8]]),
 tensor([8]),
 tensor([], size=(0, 3, 3), dtype=torch.int64))

## PyTorch tensors and NUmpy


In [108]:
###numpy to torch###
array = np.arange(1.0,10)
array, array.dtype


(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), dtype('float64'))

In [106]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor , tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [116]:
###Tensor to NUmpy
tensor = torch.ones(8)
numpy_tensor = torch.Tensor.numpy(tensor)
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take out random out of random)

In [117]:
random_seed = 4
torch.manual_seed(random_seed)
random_tensor_a = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)


tensor([[0.5596, 0.5591, 0.0915, 0.2100],
        [0.0072, 0.0390, 0.9929, 0.9131],
        [0.6186, 0.9744, 0.3189, 0.2148]])
tensor([[0.5596, 0.5591, 0.0915, 0.2100],
        [0.0072, 0.0390, 0.9929, 0.9131],
        [0.6186, 0.9744, 0.3189, 0.2148]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [118]:
## Runing tensors or pytorch on GPU

In [119]:
torch.cuda.is_available()

False